# Generated by Django 4.2.25 on 2025-10-26 16:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('profit_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeltedGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('weight_first', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن (گرم)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن الان (گرم)')),
                ('purity', models.CharField(default='750', max_length=10, verbose_name='عیار')),
                ('seller_name', models.CharField(max_length=100, verbose_name='نام فروشنده')),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن فروشنده')),
                ('assay_office', models.CharField(max_length=100, verbose_name='نام ری\u200cگیری')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلای آب\u200cشده',
                'verbose_name_plural': 'طلای آب\u200cشده\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('type_partner', models.CharField(choices=[('customer', 'مشتری'), ('partner', 'طرف\u200c حساب'), ('supplier', 'بنکدار')], max_length=20, verbose_name='نوع شخص')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('store', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
                'ordering': ['family'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ab', 'آبشده'), ('mot', 'متفرقه'), ('bracelet', 'دستبند'), ('earing', 'گوشواره'), ('neckles', 'گردنبند'), ('set', 'سرویس'), ('ring', 'انگشتر'), ('coine', 'سکه'), ('nimset', 'نیم ست'), ('medal', 'مدال'), ('zanjir', 'زنجیر'), ('other', 'سایر')], default='bracelet', max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('purity', models.CharField(default='750', max_length=10, verbose_name='عیار')),
                ('labor', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مجموع وزن (گرم)')),
                ('purity', models.CharField(default='750', max_length=10, verbose_name='عیار')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='فی ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='purchases/', verbose_name='تصویر فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(limit_choices_to={'type__in': ['partner', 'supplier']}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RetentionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('BIRTHDAY', 'تولد'), ('LOYALTY', 'وفاداری'), ('INACTIVE', 'غیرفعال\u200cها'), ('SEASONAL', 'فصلی')], default='WELCOME', max_length=20)),
                ('message', models.TextField()),
                ('send_days_after_purchase', models.PositiveIntegerField(default=0)),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال فصلی')),
                ('loyalty_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز وفاداری')),
                ('inactive_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='روزهای غیر فعال')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'ادمین'), ('Seller', 'قروشنده'), ('Accountant', 'حسابدار')], default='seller', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchaseinvoice', verbose_name='فاکتور خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='کالا')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'واریز/دریافت'), ('OUT', 'پرداخت/خرج')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transactions', to='dashboard.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGoldTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'دریافت طلا'), ('OUT', 'تحویل طلا')], max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transactions', to='dashboard.partner')),
            ],
        ),
        migrations.CreateModel(
            name='MeltedGoldTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورود به فروشگاه'), ('OUT', 'خروج از فروشگاه')], max_length=3, verbose_name='نوع تراکنش')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='منبع ورود (مثلاً خرید مستقیم یا کسری فاکتور)')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقصد خروج (مثلاً مشتری یا فروشنده)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن (گرم)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('melted_gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.meltedgold', verbose_name='طلای آب\u200cشده')),
            ],
            options={
                'verbose_name': 'تراکنش طلای آب\u200cشده فروشگاه',
                'verbose_name_plural': 'تراکنش\u200cهای طلای آب\u200cشده فروشگاه',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeltedGoldSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد طلای آب\u200cشده')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن (گرم)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
            options={
                'verbose_name': 'فروش طلای آب\u200cشده',
                'verbose_name_plural': 'فروش\u200cهای طلای آب\u200cشده',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('gold_price_per_gram', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('labor_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase', models.DateField(blank=True, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SENT', 'ارسال شد'), ('FAILED', 'ناموفق'), ('PENDING', 'در صف')], default='PENDING', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.retentioncampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to='dashboard.customer')),
            ],
        ),
    ]
