# Generated by Django 4.2.25 on 2025-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='number_store',
            field=models.CharField(default='0', max_length=30, verbose_name=' فروشنده شماره فاکتور'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ کل '),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'type_partner__in': ['partner', 'supplier']}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='فروشنده'),
        ),
    ]
