# Generated by Django 4.2.25 on 2025-10-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_person_birth_date_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
