# Generated by Django 4.2.25 on 2025-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_person_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['code'], 'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
