# Generated by Django 4.2.25 on 2025-10-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_person_options_alter_person_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to='dashboard.person'),
        ),
        migrations.AlterField(
            model_name='customercrm',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'type_partner__in': ['partner', 'supplier', 'customer']}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='فروشنده'),
        ),
    ]
