# Generated by Django 4.2.25 on 2025-10-31 15:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_campaignlog_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('income', 'درآمد'), ('expense', 'هزینه'), ('capital', 'سرمایه')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.purchaseinvoice')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_money', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('credit_money', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('debit_gold', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('credit_gold', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.journalentry')),
            ],
        ),
    ]
