# Generated by Django 4.2.25 on 2025-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_account_journalentry_journalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
