# Generated by Django 4.2.25 on 2025-11-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltedgoldtransaction',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت هر گرم (تومان)'),
        ),
        migrations.AddField(
            model_name='meltedgoldtransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ کل تراکنش (تومان)'),
        ),
        migrations.AlterField(
            model_name='meltedgoldtransaction',
            name='melted_gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.product', verbose_name='طلای آب\u200cشده'),
        ),
    ]
