# Generated by Django 4.2.25 on 2025-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_meltedgoldtransaction_price_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='وزن اولیه خرید'),
        ),
    ]
