# Generated by Django 4.2.25 on 2025-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_initial_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='labor',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
