# Generated by Django 4.2.25 on 2025-11-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_purchaseinvoice_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.account'),
        ),
    ]
