# Generated by Django 4.2.25 on 2025-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_person_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='family',
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('income', 'درآمد'), ('expense', 'هزینه'), ('capital', 'سرمایه'), ('cogs', 'بهای تمام\u200cشده')], max_length=20),
        ),
    ]
