# Generated by Django 4.2.25 on 2025-11-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_person_family_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='type',
            field=models.CharField(choices=[('gold', 'کالا طلا'), ('ab', 'آبشده'), ('mot', 'متفرقه')], default='gold', max_length=10, verbose_name='نوع خرید'),
        ),
    ]
