# Generated by Django 4.2.25 on 2025-11-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_bank_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance_gold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_items', to='dashboard.bankaccount'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='bank_statement_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='reconciled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
