# Generated by Django 4.2.25 on 2025-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_bankaccount_balance_gold_bankaccount_balance_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='swift',
        ),
        migrations.AddField(
            model_name='bank',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
