# Generated by Django 4.2.25 on 2025-11-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_bank_swift_bank_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='opening_balance',
        ),
    ]
