# Generated by Django 4.2.25 on 2025-11-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_bankaccount_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='dashboard.account'),
        ),
    ]
