# Generated by Django 4.2.25 on 2025-11-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_journalitem_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_weight2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='وزن اولیه خرید'),
        ),
    ]
