# Generated by Django 4.2.25 on 2025-11-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_product_initial_weight2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_weight2',
        ),
    ]
