# Generated by Django 4.2.25 on 2025-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_product_initial_weight2'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='gold_price_mesghal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='labor_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='meltedgoldtransaction',
            name='price_per_mesghal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت هر مثقال (تومان)'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='laborprice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='pricemesghal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='فی '),
        ),
    ]
