# Generated by Django 4.2.25 on 2025-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_invoiceitem_gold_price_mesghal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='laborprice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=14),
        ),
    ]
