# Generated by Django 4.2.25 on 2025-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_purchaseinvoice_laborprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='laborprice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=14),
        ),
    ]
