# Generated by Django 4.2.25 on 2025-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_product_laborprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='labor_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meltedgoldtransaction',
            name='price_per_mesghal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت هر مثقال (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='laborprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='laborprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
