# Generated by Django 4.2.25 on 2025-11-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_account_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام صندوق')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد صندوق')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی اولیه')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_account', to='dashboard.account')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['code'], 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب\u200cهای بانکی'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance_gold',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance_money',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='owner',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی اولیه'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد بانک'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام بانک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to='dashboard.account'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_account', to='dashboard.account'),
        ),
        migrations.AlterField(
            model_name='person',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب بانکی'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
