# Generated by Django 4.2.25 on 2025-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_cashaccount_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مجموعه'),
        ),
    ]
