# Generated by Django 4.2.25 on 2025-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_person_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.CharField(default='', max_length=100, verbose_name='نام صاحب حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی اولیه'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی اولیه'),
        ),
    ]
