# Generated by Django 4.2.25 on 2025-11-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_bankaccount_card_number_bankaccount_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام هزینه')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد هزینه')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی اولیه')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_account', to='dashboard.account')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه ها',
                'ordering': ['code'],
            },
        ),
    ]
