# Generated by Django 4.2.25 on 2025-11-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_expenseaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='dashboard.account', verbose_name='صندوق/بانک دریافت\u200cکننده')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.journalentry')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.account', verbose_name='حساب طرف مقابل')),
            ],
            options={
                'verbose_name': 'دریافت وجه',
                'verbose_name_plural': 'دریافت\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='dashboard.account', verbose_name='صندوق/بانک')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.expenseaccount', verbose_name='هزینه')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.journalentry')),
            ],
            options={
                'verbose_name': 'پرداخت وجه',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-date'],
            },
        ),
    ]
