# Generated by Django 4.2.25 on 2025-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_receipt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labor',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='laborprice',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
