# Generated by Django 4.2.25 on 2025-11-12 14:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_product_labor_alter_product_laborprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='credit_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
