# Generated by Django 4.2.25 on 2025-11-12 14:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_journalitem_credit_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='credit_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بستانکار طلا'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='credit_money',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='بستانکار پول'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدهکار طلا'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit_money',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='بدهکار پول'),
        ),
    ]
