# Generated by Django 4.2.25 on 2025-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='purity',
            field=models.CharField(default='750', max_length=10, verbose_name='عیار'),
        ),
    ]
