# Generated by Django 4.2.25 on 2025-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_product_barcode_product_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ab', 'آبشده'), ('mot', 'متفرقه'), ('bracelet', 'دستبند'), ('earing', 'گوشواره'), ('neckles', 'گردنبند'), ('set', 'سرویس'), ('ring', 'انگشتر'), ('bangle', 'النگو'), ('brba', 'دستند النگو'), ('coine', 'سکه'), ('nimset', 'نیم ست'), ('medal', 'مدال'), ('zanjir', 'زنجیر'), ('other', 'سایر')], default='bracelet', max_length=50),
        ),
    ]
